alias tmux4='tmux new -s windows4 \; split-window -h \; split-window -v \; select-pane -t 0 \; split-window -v \;'
alias tmuxa='tmux attach -t windows4'

alias nexenta1='sshpass -p nexenta ssh -l admin 10.1.24.9 -o PreferredAuthentications=password -o KexAlgorithms=+diffie-hellman-group1-sha1 -o StrictHostKeyChecking=no'
alias nexenta10='sshpass -p Nexenta10\! ssh -l admin 10.1.28.123 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta11='sshpass -p Nexenta11\!123 ssh -l admin 10.1.24.100 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta11a='sshpass -p Nexenta11\!123 ssh -l admin 10.1.24.101 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta11b='sshpass -p Nexenta11\!123 ssh -l admin 10.1.24.102 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta12='sshpass -p Nexenta12\!123 ssh -l admin 10.1.24.103 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta13='sshpass -p Nexenta13\!123 ssh -l admin 10.1.24.110 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta13a='sshpass -p Nexenta13\!123 ssh -l admin 10.1.24.111 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta13b='sshpass -p Nexenta13\!123 ssh -l admin 10.1.24.112 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta14='sshpass -p Nexenta14\!123 ssh -l admin 10.1.24.113 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta1a='sshpass -p nexenta ssh -l admin 10.1.24.1 -o PreferredAuthentications=password -o KexAlgorithms=+diffie-hellman-group1-sha1 -o StrictHostKeyChecking=no'
alias nexenta1b='sshpass -p nexenta ssh -l admin 10.1.24.2 -o PreferredAuthentications=password -o KexAlgorithms=+diffie-hellman-group1-sha1 -o StrictHostKeyChecking=no'
alias nexenta2='sshpass -p nexenta ssh -l admin 10.1.24.3 -o PreferredAuthentications=password -o KexAlgorithms=+diffie-hellman-group1-sha1 -o StrictHostKeyChecking=no'
alias nexenta3='sshpass -p Nexenta3: ssh -l admin 10.1.25.10 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta3a='sshpass -p Nexenta3: ssh -l admin 10.1.25.11 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta3b='sshpass -p Nexenta3: ssh -l admin 10.1.25.12 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta5='sshpass -p Abac@2019 ssh -l admin 10.1.28.60 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta5a='sshpass -p Abac@2019 ssh -l admin 10.1.28.61 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta5b='sshpass -p Abac@2019 ssh -l admin 10.1.28.62 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta6='sshpass -p Abac@2019 ssh -l admin 10.1.28.63 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta7='sshpass -p Nexenta1\! ssh -l admin 10.1.28.64 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta7a='sshpass -p Nexenta1\! ssh -l admin 10.1.28.65 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta7b='sshpass -p Nexenta1\! ssh -l admin 10.1.28.66 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta8='sshpass -p Nexenta8\! ssh -l admin 10.1.28.67 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta9='sshpass -p Nexenta9\! ssh -l admin 10.1.28.120 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta9a='sshpass -p Nexenta9\! ssh -l admin 10.1.28.121 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
alias nexenta9b='sshpass -p Nexenta9\! ssh -l admin 10.1.28.122 -o PreferredAuthentications=password -o StrictHostKeyChecking=no'
